"""Every detector, on a real position — plus the negative half.

⚠ A detector test needs BOTH halves. A rule with only a positive test passes
just as well when it fires on everything, and a "helpful" engine that sees an
X-Wing in every grid is exactly the failure this app was built to catch.

    python3 -m unittest discover tests
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sudoku import engine, grid as G, techniques as T
from sudoku.solver import solution

from corpus import EXAMPLES

FINDERS = {}
for _tier, _fn in T.CATALOGUE:
    FINDERS.setdefault(getattr(_fn, "__name__", "").replace("find_", ""), []).append(_fn)
# the size-parameterised families come through as lambdas; address them directly
FINDERS.update({
    "naked_pair": [lambda c: T.find_naked_subset(c, 2)],
    "naked_triple": [lambda c: T.find_naked_subset(c, 3)],
    "naked_quad": [lambda c: T.find_naked_subset(c, 4)],
    "hidden_pair": [lambda c: T.find_hidden_subset(c, 2)],
    "hidden_triple": [lambda c: T.find_hidden_subset(c, 3)],
    "hidden_quad": [lambda c: T.find_hidden_subset(c, 4)],
    "x_wing": [lambda c: T.find_fish(c, 2)],
    "swordfish": [lambda c: T.find_fish(c, 3)],
    "jellyfish": [lambda c: T.find_fish(c, 4)],
})


def _steps(technique, cells):
    ctx = T.Ctx(cells)
    out = []
    for fn in FINDERS[technique]:
        out += [s for s in fn(ctx) if s["technique"] == technique]
    return out


class TestEveryTechniqueFires(unittest.TestCase):
    """Positive half — generated by `_make` below, one test per technique."""


class TestEveryTechniqueIsSilentWhenItShould(unittest.TestCase):
    """Negative half — the same detector on the SOLVED grid must say nothing."""


def _make_positive(tech, ex):
    def t(self):
        cells = G.parse(ex["grid"])
        steps = _steps(tech, cells)
        self.assertTrue(steps, f"{tech} no longer fires on its pinned example")
        found = any(set(ex["targets"]) <= set(map(tuple, s["targets"]))
                    and set(ex["placements"]) <= set(map(tuple, s["placements"]))
                    for s in steps)
        self.assertTrue(found, f"{tech}: the pinned conclusion is gone")
    t.__name__ = f"test_{tech}"
    return t


def _make_negative(tech, ex):
    def t(self):
        cells = solution(G.parse(ex["grid"]))
        self.assertIsNotNone(cells, "pinned example lost its unique solution")
        self.assertEqual(_steps(tech, cells), [],
                         f"{tech} fires on a SOLVED grid — it is not discriminating")
    t.__name__ = f"test_{tech}_silent_on_a_solved_grid"
    return t


for _t, _ex in EXAMPLES.items():
    setattr(TestEveryTechniqueFires, f"test_{_t}", _make_positive(_t, _ex))
    setattr(TestEveryTechniqueIsSilentWhenItShould,
            f"test_{_t}_silent_on_a_solved_grid", _make_negative(_t, _ex))


class TestTheCatalogueItself(unittest.TestCase):
    def test_every_catalogued_technique_has_a_french_label(self):
        missing = [k for k in EXAMPLES if k not in T.LABELS_FR]
        self.assertEqual(missing, [])

    def test_every_labelled_technique_has_a_pinned_example(self):
        # a technique with no example is a technique nobody has ever seen fire
        self.assertEqual(sorted(set(T.LABELS_FR) - set(EXAMPLES)), [])

    def test_no_step_is_ever_empty(self):
        for tech, ex in EXAMPLES.items():
            for s in _steps(tech, G.parse(ex["grid"])):
                self.assertTrue(s["targets"] or s["placements"],
                                f"{tech} yielded a step that concludes nothing")

    def test_every_why_points_at_something_the_highlight_shows(self):
        """⚠ The sentence is GENERATED from the structure. If it stops naming
        either a highlighted cell (pattern OR target) or the unit it points at, prose and
        the highlight have drifted — and that drift is invisible until someone
        reads a sentence about cells the board isn't showing.

        The line patterns (fish) legitimately speak in lines rather than cells
        ("le 7 des lignes 1, 3, 5, 8"), so the unit may be named in the plural
        form instead of `unit_name_fr`'s singular. Both spellings count; saying
        nothing does not.
        """
        for tech, ex in EXAMPLES.items():
            for s in _steps(tech, G.parse(ex["grid"]))[:1]:
                why = s["why_fr"]
                shown = list(s["cells"]) + [i for i, _ in s["targets"]] \
                    + [i for i, _ in s["placements"]]
                hit = any(G.name(i) in why for i in shown)
                unit = False
                if s["unit"] is not None:
                    kind, n = G.UNIT_KIND[s["unit"]]
                    word = {"row": "ligne", "col": "colonne", "box": "boîte"}[kind]
                    unit = (G.unit_name_fr(s["unit"]) in why
                            or (word in why and str(n + 1) in why))
                self.assertTrue(hit or unit, f"{tech}: {why}")


class TestSafety(unittest.TestCase):
    def test_no_detector_ever_removes_a_TRUE_candidate(self):
        """The invariant that subsumes every other test here."""
        for tech, ex in EXAMPLES.items():
            cells = G.parse(ex["grid"])
            sol = solution(cells)
            for s in _steps(tech, cells):
                for i, d in s["targets"]:
                    self.assertNotEqual(sol[i], d,
                                        f"{tech} would remove the true {d} from {G.name(i)}")
                for i, d in s["placements"]:
                    self.assertEqual(sol[i], d,
                                     f"{tech} would place a wrong {d} in {G.name(i)}")


if __name__ == "__main__":
    unittest.main()
